# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['waterRPA.py'],
    pathex=[
        '.',
    ],
    binaries=[],
    datas=[],
    hiddenimports=[
        'timeout',
        'inspector',
        'autostart',
        'template_manager',
        'PySide6.QtWidgets',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'pyautogui',
        'pyperclip',
        'PIL',
        'psutil',
        'win32gui',
        'win32con',
        'win32process',
        'win32api',
        'winreg',
        'ctypes',
        'json',
        'time',
        'threading',
        'traceback',
        'os',
        'sys',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='WaterRPA',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)